import type { FieldKey } from "../types";

export interface FieldDefinition {
  key: FieldKey;
  label: string;
  group: "summary" | "payment";
}

export const fieldDefinitions: FieldDefinition[] = [
  { key: "advertiser", label: "Advertiser", group: "summary" },
  { key: "publisher", label: "Publisher", group: "summary" },
  { key: "contractNumber", label: "合同编号", group: "summary" },
  { key: "ioNumber", label: "IO 编号", group: "summary" },
  { key: "projectBrand", label: "项目 / 品牌", group: "summary" },
  { key: "platformChannel", label: "平台 / 频道", group: "summary" },
  { key: "effectiveDate", label: "生效日期", group: "summary" },
  { key: "campaignPeriod", label: "Campaign Period", group: "summary" },
  {
    key: "projectTotalFees",
    label: "Project Total Fees",
    group: "payment",
  },
  {
    key: "invoiceIssuePeriod",
    label: "Invoice Issue Period",
    group: "payment",
  },
  { key: "paymentTerm", label: "Payment Term", group: "payment" },
  { key: "paymentMethod", label: "Payment Method", group: "payment" },
  { key: "transferFee", label: "Transfer Fee", group: "payment" },
  {
    key: "beneficiaryAccount",
    label: "Beneficiary / Bank Account",
    group: "payment",
  },
];

export const aliases = {
  advertiser: [
    "广告主",
    "客户",
    "品牌方",
    "甲方",
    "Advertiser",
    "Advertiser Name",
    "Client",
    "Client Name",
    "Brand",
    "Company",
  ],
  publisher: [
    "发布方",
    "达人",
    "创作者",
    "服务提供方",
    "乙方",
    "Publisher",
    "Publisher Name",
    "Creator",
    "Creator Name",
    "Influencer",
    "Influencer Name",
    "Service Provider",
    "Service Provider Name",
  ],
  contractNumber: [
    "合同编号",
    "协议编号",
    "Contract Number",
    "Contract No.",
    "Contract No",
    "Agreement Number",
    "Agreement ID",
  ],
  ioNumber: [
    "IO 编号",
    "IO编号",
    "订单编号",
    "投放订单号",
    "IO Number",
    "IO No.",
    "IO No",
    "Insertion Order Number",
    "Order Number",
  ],
  projectName: [
    "项目名称",
    "推广项目",
    "活动名称",
    "Project Name",
    "Campaign Name",
    "Campaign Details",
  ],
  brandName: ["品牌", "Brand"],
  platform: ["平台", "发布平台", "Platform", "Publishing Platform"],
  channelName: ["频道", "频道名称", "Channel", "Channel Name"],
  handle: ["账号", "社媒账号", "Handle", "Channel Handle"],
  channelUrl: ["主页链接", "频道链接", "Channel Link", "Channel URL"],
  effectiveDate: [
    "生效日期",
    "协议生效日",
    "Effective Date",
    "Agreement Effective Date",
  ],
  signatureDate: ["签署日期", "签字日期", "Signature Date", "Signed Date"],
  campaignPeriod: [
    "活动周期",
    "项目周期",
    "推广周期",
    "服务周期",
    "Campaign Period",
    "Campaign Date",
    "Service Period",
  ],
  startDate: ["开始日期", "Start Date", "Campaign Start Date"],
  endDate: ["结束日期", "End Date", "Campaign End Date"],
  projectTotalFees: [
    "项目总费用",
    "合同金额",
    "服务费",
    "Project Total Fees",
    "Total Fees",
    "Contract Amount",
    "Service Fee",
  ],
  invoiceIssuePeriod: [
    "Invoice 开具期限",
    "Invoice 提交期限",
    "发票开具期限",
    "发票提交期限",
    "Invoice Issue Period",
    "Invoice Submission Period",
    "Invoice Date",
  ],
  paymentTerm: [
    "付款期限",
    "支付期限",
    "Payment Term",
    "Payment Terms",
    "Payment Due",
  ],
  paymentMethod: ["付款方式", "支付方式", "Payment Method", "Method of Payment"],
  transferFee: [
    "转账手续费",
    "银行手续费",
    "Transfer Fee",
    "Bank Charge",
    "Bank Fee",
  ],
  beneficiaryAccount: [
    "收款主体",
    "收款账户",
    "银行账户",
    "账户快照",
    "Beneficiary",
    "Beneficiary Name",
    "Bank Account",
    "Account Number",
    "IBAN",
  ],
} as const;

export const labelsByKey = new Map(
  fieldDefinitions.map((definition) => [definition.key, definition.label]),
);
