import type { InvoiceEntity, Payout } from './types';

export type SystemRoleKey = 'media' | 'pm' | 'finance' | 'admin' | 'owner' | 'project';
export type LoginSessionPolicy = 'single_device' | 'multi_device';

export const ROLE_LOGIN_SESSION_POLICY: Record<SystemRoleKey, LoginSessionPolicy> = {
  media: 'multi_device',
  pm: 'multi_device',
  admin: 'multi_device',
  project: 'single_device',
  owner: 'single_device',
  finance: 'single_device',
};

export const supportsMultiDeviceLogin = (roleKey: SystemRoleKey) => (
  ROLE_LOGIN_SESSION_POLICY[roleKey] === 'multi_device'
);

export type SystemUser = {
  account: string;
  name: string;
  email: string;
  initials: string;
  roleKey: SystemRoleKey;
  role: string;
  scopeName?: string;
  isDemo?: boolean;
};

export const DEMO_SYSTEM_USERS: SystemUser[] = [
  { account: 'media.demo', name: '媒介体验账号', email: 'media@comets.example', initials: 'ME', roleKey: 'media', role: '媒介账号', scopeName: '媒介演示用户 A', isDemo: true },
  { account: 'pm.demo', name: 'PM 体验账号', email: 'pm@comets.example', initials: 'PM', roleKey: 'pm', role: 'PM 账号', scopeName: 'PM 演示用户 A', isDemo: true },
  { account: 'project.demo', name: '项目负责人体验账号', email: 'project@comets.example', initials: 'PJ', roleKey: 'project', role: '项目负责人账号', isDemo: true },
  { account: 'owner.demo', name: '老板体验账号', email: 'owner@comets.example', initials: 'OW', roleKey: 'owner', role: '老板账号', isDemo: true },
  { account: 'finance.demo', name: '财务体验账号', email: 'finance@comets.example', initials: 'FI', roleKey: 'finance', role: '财务账号', isDemo: true },
  { account: 'admin.demo', name: '管理员体验账号', email: 'admin@comets.example', initials: 'AD', roleKey: 'admin', role: '管理员账号', isDemo: true },
];

export const CURRENT_USER = DEMO_SYSTEM_USERS.find((user) => user.roleKey === 'finance')!;

export const SYSTEM_USERS: SystemUser[] = DEMO_SYSTEM_USERS;

export const PM_USERS = SYSTEM_USERS.filter((user) => user.roleKey === 'pm');

export type ProjectFixture = {
  id: string;
  name: string;
  brand: string;
  media: string;
  pm: string;
  creators: number;
  budget: string;
  projectStatus: string;
  requestStatus: string;
  requestFilter: 'pending' | 'processed';
  paymentOrder: string;
};

export const PROJECT_FIXTURES: ProjectFixture[] = [
  {
    id: 'PRJ-301164',
    name: '#301164 DCD欧美&东南亚地区创作者生态项目（26年4-6月）',
    brand: '网易',
    media: '媒介演示用户 A',
    pm: 'PM 演示用户 A',
    creators: 18,
    budget: 'USD 48,000',
    projectStatus: '已完成',
    requestStatus: '已完成',
    requestFilter: 'processed',
    paymentOrder: 'PAY-301164-01',
  },
  {
    id: 'PRJ-260727-02',
    name: '燕云十六声',
    brand: 'NetEase Games',
    media: '媒介演示用户 B',
    pm: 'PM 演示用户 B',
    creators: 16,
    budget: 'USD 36,800',
    projectStatus: '执行中',
    requestStatus: '待审批',
    requestFilter: 'pending',
    paymentOrder: 'PAY-260727-02',
  },
  {
    id: 'PRJ-260727-03',
    name: 'Once Human主机上线KOL合作项目',
    brand: '网易',
    media: '媒介演示用户 C',
    pm: 'PM 演示用户 C',
    creators: 20,
    budget: 'USD 42,500',
    projectStatus: '执行中',
    requestStatus: '财务审批中',
    requestFilter: 'pending',
    paymentOrder: 'PAY-260727-03',
  },
  {
    id: 'PRJ-260727-04',
    name: '原神-欧美KOC-6.7版本',
    brand: '米哈游',
    media: '媒介演示用户 A',
    pm: 'PM 演示用户 A',
    creators: 24,
    budget: 'USD 31,200',
    projectStatus: '执行中',
    requestStatus: 'PM 审批中',
    requestFilter: 'pending',
    paymentOrder: 'PAY-260727-04',
  },
  {
    id: 'PRJ-260727-05',
    name: '恋与深空欧美KOC - 7月',
    brand: 'Infolder Games',
    media: '媒介演示用户 B',
    pm: 'PM 演示用户 B',
    creators: 12,
    budget: 'USD 18,600',
    projectStatus: '执行中',
    requestStatus: '待补资料',
    requestFilter: 'pending',
    paymentOrder: 'PAY-260727-05',
  },
  {
    id: 'PRJ-260727-06',
    name: '永劫无间欧美竞品生态KOC 2026.07 - 2026.08',
    brand: 'NetEase Games',
    media: '媒介演示用户 C',
    pm: 'PM 演示用户 C',
    creators: 15,
    budget: 'USD 27,000',
    projectStatus: '执行中',
    requestStatus: '待打款',
    requestFilter: 'pending',
    paymentOrder: 'PAY-260727-06',
  },
  {
    id: 'PRJ-260727-07',
    name: 'Racing Master NA/EU KOC 4-6月',
    brand: '网易游戏',
    media: '媒介演示用户 A',
    pm: 'PM 演示用户 A',
    creators: 14,
    budget: 'USD 32,000',
    projectStatus: '已完成',
    requestStatus: '已完成',
    requestFilter: 'processed',
    paymentOrder: 'PAY-260727-07',
  },
  {
    id: 'PRJ-260727-08',
    name: 'Marvel Rivals S8前瞻直播',
    brand: '网易',
    media: '媒介演示用户 B',
    pm: 'PM 演示用户 B',
    creators: 8,
    budget: 'USD 24,000',
    projectStatus: '已完成',
    requestStatus: '财务审批中',
    requestFilter: 'pending',
    paymentOrder: 'PAY-260727-08',
  },
  {
    id: 'PRJ-260727-09',
    name: '永劫无间欧美竞品生态KOC 2026.06 - 2026.07',
    brand: 'NetEase Games',
    media: '媒介演示用户 C',
    pm: 'PM 演示用户 C',
    creators: 13,
    budget: 'USD 23,400',
    projectStatus: '已完成',
    requestStatus: '已完成',
    requestFilter: 'processed',
    paymentOrder: 'PAY-260727-09',
  },
  {
    id: 'PRJ-260727-10',
    name: '杖剑传说KOL',
    brand: '雷霆游戏',
    media: '媒介演示用户 A',
    pm: 'PM 演示用户 A',
    creators: 6,
    budget: 'USD 12,600',
    projectStatus: '已完成',
    requestStatus: '待审批',
    requestFilter: 'pending',
    paymentOrder: 'PAY-260727-10',
  },
  {
    id: 'PRJ-260727-11',
    name: '逆水寒测试项目',
    brand: '网易游戏',
    media: '媒介演示用户 B',
    pm: 'PM 演示用户 B',
    creators: 5,
    budget: 'USD 9,800',
    projectStatus: '已完成',
    requestStatus: '已完成',
    requestFilter: 'processed',
    paymentOrder: 'PAY-260727-11',
  },
  {
    id: 'PRJ-260727-12',
    name: '巅峰极速欧美KOL',
    brand: '网易',
    media: '媒介演示用户 C',
    pm: 'PM 演示用户 C',
    creators: 10,
    budget: 'USD 28,000',
    projectStatus: '已完成',
    requestStatus: '已完成',
    requestFilter: 'processed',
    paymentOrder: 'PAY-260727-12',
  },
  {
    id: 'PRJ-260801-01',
    name: '蛋仔派对欧美KOL创作者项目（2026年8月）',
    brand: '网易',
    media: '媒介演示用户 A',
    pm: 'PM 演示用户 A',
    creators: 11,
    budget: 'USD 21,800',
    projectStatus: '执行中',
    requestStatus: '财务审批中',
    requestFilter: 'pending',
    paymentOrder: 'PAY-260801-01',
  },
  {
    id: 'PRJ-260801-02',
    name: '第五人格全球创作者合作计划 S41',
    brand: '网易游戏',
    media: '媒介演示用户 B',
    pm: 'PM 演示用户 B',
    creators: 9,
    budget: 'USD 19,600',
    projectStatus: '执行中',
    requestStatus: '财务审批中',
    requestFilter: 'pending',
    paymentOrder: 'PAY-260801-02',
  },
  {
    id: 'PRJ-260801-03',
    name: '漫威争锋 S9 欧美直播合作',
    brand: '网易',
    media: '媒介演示用户 C',
    pm: 'PM 演示用户 C',
    creators: 7,
    budget: 'USD 25,200',
    projectStatus: '执行中',
    requestStatus: '待打款',
    requestFilter: 'pending',
    paymentOrder: 'PAY-260801-03',
  },
  {
    id: 'PRJ-260801-04',
    name: '七日世界东南亚 KOC 口碑项目',
    brand: 'NetEase Games',
    media: '媒介演示用户 A',
    pm: 'PM 演示用户 A',
    creators: 13,
    budget: 'USD 29,400',
    projectStatus: '执行中',
    requestStatus: '待打款',
    requestFilter: 'pending',
    paymentOrder: 'PAY-260801-04',
  },
  {
    id: 'PRJ-260801-05',
    name: '荒野行动日韩创作者合作（2026 Q2）',
    brand: '网易游戏',
    media: '媒介演示用户 B',
    pm: 'PM 演示用户 B',
    creators: 10,
    budget: 'USD 22,700',
    projectStatus: '已完成',
    requestStatus: '已完成',
    requestFilter: 'processed',
    paymentOrder: 'PAY-260801-05',
  },
  {
    id: 'PRJ-260801-06',
    name: '萤火突击欧美 KOL 内容合作',
    brand: 'NetEase Games',
    media: '媒介演示用户 C',
    pm: 'PM 演示用户 C',
    creators: 8,
    budget: 'USD 18,900',
    projectStatus: '已完成',
    requestStatus: '已完成',
    requestFilter: 'processed',
    paymentOrder: 'PAY-260801-06',
  },
  {
    id: 'PRJ-260801-07',
    name: '逆水寒手游海外主播测试项目',
    brand: '网易游戏',
    media: '媒介演示用户 A',
    pm: 'PM 演示用户 A',
    creators: 6,
    budget: 'USD 14,800',
    projectStatus: '执行中',
    requestStatus: '已退回',
    requestFilter: 'pending',
    paymentOrder: 'PAY-260801-07',
  },
  {
    id: 'PRJ-260801-08',
    name: '永劫无间东南亚 KOC（2026年8月）',
    brand: 'NetEase Games',
    media: '媒介演示用户 B',
    pm: 'PM 演示用户 B',
    creators: 12,
    budget: 'USD 26,300',
    projectStatus: '执行中',
    requestStatus: '已退回',
    requestFilter: 'pending',
    paymentOrder: 'PAY-260801-08',
  },
];

const PROJECT_FIXTURE_BY_ID = new Map(PROJECT_FIXTURES.map((project) => [project.id, project]));

export const getProjectFixture = (projectId: string) => PROJECT_FIXTURE_BY_ID.get(projectId);

const getProjectName = (projectId: string) => getProjectFixture(projectId)?.name ?? '待关联项目';

export const resolveSystemUser = (value: string): SystemUser | undefined => {
  const normalizedValue = value.trim().toLowerCase();
  return SYSTEM_USERS.find((user) => (
    user.account.toLowerCase() === normalizedValue
    || user.email.toLowerCase() === normalizedValue
    || user.name.toLowerCase() === normalizedValue
  ));
};

export const authenticateSystemUser = (account: string, password: string): { user?: SystemUser; error?: string } => {
  const user = resolveSystemUser(account);
  if (!user) return { error: '账号不存在，请检查账号或工作邮箱。' };
  if (!password) return { error: '请输入登录密码。' };
  return { user };
};

export const INITIAL_INVOICE_ENTITY: InvoiceEntity = {
  name: 'COMETS INTERNATIONAL LIMITED',
  address: 'Unit 04-05, 16th Floor, The Broadway No. 54-62 Lockhart Road, Wanchai, Hong Kong, China',
};

const INITIAL_PAYOUT_FIXTURES: Array<Omit<Payout, 'creatorId' | 'collaborationId'>> = [
  {
    id: 'pay-001',
    creator: '@MinaKato',
    handle: '@MinaKato',
    initials: 'MK',
    projectId: 'PRJ-260727-03',
    project: getProjectName('PRJ-260727-03'),
    deliverable: '直播 2 场 + 短视频 3 条',
    contract: 'CON-260718-01',
    invoice: 'INV-240718',
    provider: 'Airwallex',
    currency: 'USD',
    amount: 3240,
    account: '0000000001',
    status: '待财务复核',
    accent: '#f59e0b',
  },
  {
    id: 'pay-008',
    creator: 'Yuki Tanaka',
    handle: '@yuki.tokyo',
    initials: 'YT',
    projectId: 'PRJ-260727-03',
    project: getProjectName('PRJ-260727-03'),
    deliverable: 'Instagram Reels 2 条 + 图文内容 1 组',
    contract: 'CON-260718-01',
    invoice: 'INV-240717',
    provider: 'PayPal',
    currency: 'USD',
    amount: 1480,
    account: 'yuki.tanaka@example.com',
    status: '待财务复核',
    accent: '#ec4899',
  },
  {
    id: 'pay-009',
    creator: 'Camila Costa',
    handle: '@camila.beauty',
    initials: 'CC',
    projectId: 'PRJ-260727-03',
    project: getProjectName('PRJ-260727-03'),
    deliverable: 'TikTok 短视频 3 条',
    contract: 'CON-260718-01',
    invoice: 'INV-240715',
    provider: 'PayMax',
    currency: 'EUR',
    amount: 2160,
    account: '0000000002',
    status: '待财务复核',
    accent: '#f97316',
  },
  {
    id: 'pay-010',
    creator: 'Oliver Chen',
    handle: '@oliver.tech',
    initials: 'OC',
    projectId: 'PRJ-260727-03',
    project: getProjectName('PRJ-260727-03'),
    deliverable: 'YouTube 长视频 1 条',
    contract: 'CON-260718-01',
    invoice: 'INV-240713',
    provider: 'Airwallex',
    currency: 'USD',
    amount: 3750,
    account: '0000000003',
    status: '待财务复核',
    accent: '#06b6d4',
  },
  {
    id: 'pay-002',
    creator: 'Alex Ruiz',
    handle: '@alexbuilds',
    initials: 'AR',
    projectId: 'PRJ-260727-06',
    project: getProjectName('PRJ-260727-06'),
    deliverable: 'YouTube 长视频 1 条',
    contract: 'CON-260714-03',
    invoice: 'INV-240714',
    provider: 'PayMax',
    currency: 'EUR',
    amount: 1850,
    account: 'ES00 DEMO 0000 0000 0000 0000',
    status: '等待付款',
    accent: '#3b82f6',
  },
  {
    id: 'pay-011',
    creator: 'Hannah Lee',
    handle: '@hannah.home',
    initials: 'HL',
    projectId: 'PRJ-260727-06',
    project: getProjectName('PRJ-260727-06'),
    deliverable: 'Instagram Reels 2 条',
    contract: 'CON-260714-03',
    invoice: 'INV-240710',
    provider: 'PayPal',
    currency: 'USD',
    amount: 1320,
    account: 'hannah.lee@example.com',
    status: '等待付款',
    accent: '#8b5cf6',
  },
  {
    id: 'pay-003',
    creator: 'Nika',
    handle: '@nika.spark',
    initials: 'NK',
    projectId: 'PRJ-260727-07',
    project: getProjectName('PRJ-260727-07'),
    deliverable: 'TikTok Spark 视频 4 条',
    contract: 'CON-260625-06',
    invoice: 'INV-240709',
    provider: 'Airwallex',
    currency: 'USD',
    amount: 920,
    account: '0000000004',
    status: '信息异常',
    accent: '#ef4444',
    issue: '泰国本地转账路由代码尚未通过校验',
  },
  {
    id: 'pay-012',
    creator: 'Luca Bianchi',
    handle: '@luca.style',
    initials: 'LB',
    projectId: 'PRJ-260727-06',
    project: getProjectName('PRJ-260727-06'),
    deliverable: 'Instagram Reels 2 条 + TikTok 视频 2 条',
    contract: 'CON-260714-03',
    invoice: 'INV-240706',
    provider: 'PayMax',
    currency: 'EUR',
    amount: 2980,
    account: 'IT00 DEMO 0000 0000 0000 0000',
    status: '付款处理中',
    accent: '#6366f1',
  },
  {
    id: 'pay-013',
    creator: 'Emily Wong',
    handle: '@emily.travel',
    initials: 'EW',
    projectId: 'PRJ-260727-04',
    project: getProjectName('PRJ-260727-04'),
    deliverable: 'YouTube Vlog 1 条 + Instagram Story 4 条',
    contract: 'CON-260711-02',
    invoice: 'INV-240705',
    provider: 'Airwallex',
    currency: 'USD',
    amount: 2440,
    account: '000000005',
    status: '已退回',
    accent: '#ef4444',
    issue: '财务退回：Invoice 缺少达人签字页',
    returnReason: 'Invoice 缺少达人签字页',
  },
  {
    id: 'pay-004',
    creator: '@Luna_J',
    handle: '@Luna_J',
    initials: 'LJ',
    projectId: 'PRJ-260727-04',
    project: getProjectName('PRJ-260727-04'),
    deliverable: 'Reels 2 条 + Story 6 条',
    contract: 'CON-260711-02',
    invoice: 'INV-240702',
    provider: 'Airwallex',
    currency: 'USD',
    amount: 5600,
    account: '0000000006',
    status: '飞书审批中',
    accent: '#a855f7',
  },
  {
    id: 'pay-005',
    creator: 'Kenji Mori',
    handle: '@kenji.moves',
    initials: 'KM',
    projectId: 'PRJ-260727-07',
    project: getProjectName('PRJ-260727-07'),
    deliverable: 'YouTube 测评视频 1 条',
    contract: 'CON-260625-06',
    invoice: 'INV-240628',
    provider: 'Airwallex',
    currency: 'USD',
    amount: 4100,
    account: '0000000007',
    status: '已付款',
    accent: '#22c55e',
    paidAt: '2026-07-16 14:32',
  },
  {
    id: 'pay-006',
    creator: 'Sofia M.',
    handle: '@sofia.daily',
    initials: 'SM',
    projectId: 'PRJ-260727-07',
    project: getProjectName('PRJ-260727-07'),
    deliverable: 'TikTok 短视频 3 条',
    contract: 'CON-260625-06',
    invoice: 'INV-240621',
    provider: 'PayMax',
    currency: 'EUR',
    amount: 2680,
    account: '000000000008',
    status: '已付款',
    accent: '#22c55e',
    paidAt: '2026-07-15 09:18',
  },
  {
    id: 'pay-007',
    creator: 'Marc O.',
    handle: '@marcframes',
    initials: 'MO',
    projectId: 'PRJ-260727-04',
    project: getProjectName('PRJ-260727-04'),
    deliverable: 'Instagram 图文 2 组',
    contract: 'CON-260711-02',
    invoice: 'INV-240617',
    provider: 'PayPal',
    currency: 'USD',
    amount: 1260,
    account: '待补充 PayPal 邮箱',
    status: '已退回',
    accent: '#ef4444',
    issue: '财务退回：Invoice 收款主体与合同不一致',
    returnReason: 'Invoice 收款主体与合同不一致',
  },
  {
    id: 'pay-014',
    creator: '@MinaKato',
    handle: '@MinaKato',
    initials: 'MK',
    projectId: 'PRJ-260801-01',
    project: getProjectName('PRJ-260801-01'),
    deliverable: 'TikTok 短视频 2 条 + Instagram Reels 1 条',
    contract: 'CON-260801-01',
    invoice: 'INV-240801',
    provider: 'Airwallex',
    currency: 'USD',
    amount: 1980,
    account: '0000000001',
    status: '待财务复核',
    accent: '#f59e0b',
  },
  {
    id: 'pay-015',
    creator: 'Yuki Tanaka',
    handle: '@yuki.tokyo',
    initials: 'YT',
    projectId: 'PRJ-260801-02',
    project: getProjectName('PRJ-260801-02'),
    deliverable: 'Instagram Reels 2 条 + Story 3 条',
    contract: 'CON-260801-02',
    invoice: 'INV-240802',
    provider: 'PayPal',
    currency: 'USD',
    amount: 1740,
    account: 'yuki.tanaka@example.com',
    status: '待财务复核',
    accent: '#ec4899',
  },
  {
    id: 'pay-016',
    creator: 'Camila Costa',
    handle: '@camila.beauty',
    initials: 'CC',
    projectId: 'PRJ-260801-03',
    project: getProjectName('PRJ-260801-03'),
    deliverable: 'Twitch 直播 2 场 + TikTok 精剪 2 条',
    contract: 'CON-260801-03',
    invoice: 'INV-240803',
    provider: 'PayMax',
    currency: 'EUR',
    amount: 2360,
    account: '0000000002',
    status: '等待付款',
    accent: '#f97316',
  },
  {
    id: 'pay-017',
    creator: 'Oliver Chen',
    handle: '@oliver.tech',
    initials: 'OC',
    projectId: 'PRJ-260801-04',
    project: getProjectName('PRJ-260801-04'),
    deliverable: 'YouTube 长视频 1 条 + Shorts 2 条',
    contract: 'CON-260801-04',
    invoice: 'INV-240804',
    provider: 'Airwallex',
    currency: 'USD',
    amount: 2890,
    account: '0000000003',
    status: '付款处理中',
    accent: '#06b6d4',
  },
  {
    id: 'pay-018',
    creator: 'Kenji Mori',
    handle: '@kenji.moves',
    initials: 'KM',
    projectId: 'PRJ-260801-05',
    project: getProjectName('PRJ-260801-05'),
    deliverable: 'YouTube 测评视频 1 条 + X 图文 2 组',
    contract: 'CON-260801-05',
    invoice: 'INV-240805',
    provider: 'Airwallex',
    currency: 'USD',
    amount: 3150,
    account: '0000000007',
    status: '已付款',
    accent: '#22c55e',
    paidAt: '2026-07-25 16:20',
  },
  {
    id: 'pay-019',
    creator: 'Hannah Lee',
    handle: '@hannah.home',
    initials: 'HL',
    projectId: 'PRJ-260801-06',
    project: getProjectName('PRJ-260801-06'),
    deliverable: 'Instagram Reels 2 条 + Story 4 条',
    contract: 'CON-260801-06',
    invoice: 'INV-240806',
    provider: 'PayPal',
    currency: 'USD',
    amount: 1460,
    account: 'hannah.lee@example.com',
    status: '已付款',
    accent: '#22c55e',
    paidAt: '2026-07-26 10:08',
  },
  {
    id: 'pay-020',
    creator: 'Marc O.',
    handle: '@marcframes',
    initials: 'MO',
    projectId: 'PRJ-260801-07',
    project: getProjectName('PRJ-260801-07'),
    deliverable: 'Instagram 图文 2 组 + Reels 1 条',
    contract: 'CON-260801-07',
    invoice: 'INV-240807',
    provider: 'PayPal',
    currency: 'USD',
    amount: 1320,
    account: 'marc.frames@example.com',
    status: '已退回',
    accent: '#ef4444',
    issue: '财务退回：合同金额与 Invoice 金额不一致',
    returnReason: '合同金额与 Invoice 金额不一致',
  },
  {
    id: 'pay-021',
    creator: 'Emily Wong',
    handle: '@emily.travel',
    initials: 'EW',
    projectId: 'PRJ-260801-08',
    project: getProjectName('PRJ-260801-08'),
    deliverable: 'YouTube Vlog 1 条 + TikTok 短视频 2 条',
    contract: 'CON-260801-08',
    invoice: 'INV-240808',
    provider: 'Airwallex',
    currency: 'USD',
    amount: 2180,
    account: '000000005',
    status: '已退回',
    accent: '#ef4444',
    issue: '财务退回：收款账号开户名与合同签约主体不一致',
    returnReason: '收款账号开户名与合同签约主体不一致',
  },
];

const PAYOUT_STABLE_LINKS: Record<string, Pick<Payout, 'creatorId' | 'collaborationId'>> = {
  'pay-001': { creatorId: 'creator-mina', collaborationId: 'collaboration-pay-001' },
  'pay-002': { creatorId: 'creator-alex', collaborationId: 'collaboration-pay-002' },
  'pay-003': { creatorId: 'creator-nika', collaborationId: 'collaboration-pay-003' },
  'pay-004': { creatorId: 'creator-luna', collaborationId: 'collaboration-pay-004' },
  'pay-005': { creatorId: 'creator-kenji', collaborationId: 'collaboration-pay-005' },
  'pay-006': { creatorId: 'creator-sofia', collaborationId: 'collaboration-pay-006' },
  'pay-007': { creatorId: 'creator-marc', collaborationId: 'collaboration-pay-007' },
  'pay-008': { creatorId: 'creator-yuki', collaborationId: 'collaboration-pay-008' },
  'pay-009': { creatorId: 'creator-camila', collaborationId: 'collaboration-pay-009' },
  'pay-010': { creatorId: 'creator-oliver', collaborationId: 'collaboration-pay-010' },
  'pay-011': { creatorId: 'creator-hannah', collaborationId: 'collaboration-pay-011' },
  'pay-012': { creatorId: 'creator-luca', collaborationId: 'collaboration-pay-012' },
  'pay-013': { creatorId: 'creator-emily', collaborationId: 'collaboration-pay-013' },
  'pay-014': { creatorId: 'creator-mina', collaborationId: 'collaboration-pay-014' },
  'pay-015': { creatorId: 'creator-yuki', collaborationId: 'collaboration-pay-015' },
  'pay-016': { creatorId: 'creator-camila', collaborationId: 'collaboration-pay-016' },
  'pay-017': { creatorId: 'creator-oliver', collaborationId: 'collaboration-pay-017' },
  'pay-018': { creatorId: 'creator-kenji', collaborationId: 'collaboration-pay-018' },
  'pay-019': { creatorId: 'creator-hannah', collaborationId: 'collaboration-pay-019' },
  'pay-020': { creatorId: 'creator-marc', collaborationId: 'collaboration-pay-020' },
  'pay-021': { creatorId: 'creator-emily', collaborationId: 'collaboration-pay-021' },
};

export const INITIAL_PAYOUTS: Payout[] = INITIAL_PAYOUT_FIXTURES.map((payout) => ({
  ...payout,
  ...PAYOUT_STABLE_LINKS[payout.id],
}));

export const PAGE_TITLES = {
  dashboard: '数据工作台',
  'payment-workbench': '付款工作台',
  projects: '我的项目',
  requests: '请款项目',
  contracts: '合同管理',
  creators: '达人档案',
  collaborations: '合作名单',
  invoice: 'Invoice 管理',
  'invoice-create': '生成 Invoice',
  batches: '付款批次',
  'new-batch': '新建付款批次',
  transactions: '交易记录',
  organization: '组织信息',
  channels: '渠道设置',
  'system-settings': '系统设置',
  notifications: '通知',
} as const;

export const formatAmount = (payout: Pick<Payout, 'currency' | 'amount'>) =>
  `${payout.currency} ${payout.amount.toLocaleString('en-US', {
    minimumFractionDigits: 0,
    maximumFractionDigits: 2,
  })}`;
